config/routes.rb
Rails.application.routes.draw do
  resources :routes

  devise_for :users, :controllers => { :omniauth_callbacks => "devise/custom/omniauth_callbacks" }
  resources :issues do
    get 'clear', on: :collection
  end

  root to: 'static#index'

  get 'welcome' => 'static#welcome', as: :welcome
  get 'static/tweets'
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  after_validation :geocode
  geocoded_by :full_address

  after_create :notify_users

  def full_address
    "#{self.suburb}, SA"
  end

  def as_json(options)
    # this example DOES NOT ignore the user's options
    # super({:only => [:email, :handle]}.merge(options))

    {lat: latitude, lng: longitude, description: description.humanize, issue_date: issue_date.strftime("%d %b")}
  end

  def notify_users
    if source.blank?
      User.all.each do |user|
        Notification.create(issue: self, user: user)
      end
    end
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :issue

  validates_presence_of :issue, :user

  after_create :sms_user

  def sms_user
    require 'smsglobal'
    sender = SmsGlobal::Sender.new :user => '92lrp5ps', password: 'd3YwQQVz'

    text = "Traffic issue in #{self.issue.suburb}: #{self.issue.description.strip}. \n"
    text = text + "By the way - heard of EasyFuel? Save 10, 20, 30c/L off petrol and more!"

    sender.send_text text, self.user.mobile, '0435129029'
  end
end

app/models/route.rb
class Route < ActiveRecord::Base
end

app/models/street.rb
class Street < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend Facebook
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :mobile)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :mobile)}
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.where(issue_date: [(Date.today - 3.months) .. Date.tomorrow]).to_json
    render json: @issues
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @routes }
    end
  end

  def clear
    Issue.where(user: current_user).destroy_all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @route }
    end
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render json: @route, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:route_from, :route_to, :start_time, :end_time)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    redirect_to welcome_path if user_signed_in?
  end

  def welcome

  end

  def tweets
    @twitter_entries = Issue.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nice_controller_name
    name = ([Object].include? controller.class.parent) ? controller_name : "#{controller.class.parent}_#{controller_name}" 
    name.demodulize.gsub("Controller", "").underscore
  end

  def json_for(target, options = {})
    options[:scope] ||= self
    options[:url_options] ||= url_options
    target.active_model_serializer.new(target, options).to_json
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/issues/index.html.erb
<h1>Issues#index</h1>
<p>Find me in app/views/issues/index.html.erb</p>

app/views/layouts/_facebook.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '735274106560993',
      xfbml      : true,
      version    : 'v2.1'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_header.html.erb
<header>
    <nav class="navigation navigation-header">
        <div class="container">
            <div class="navigation-brand">
                <div class="brand-logo">
                    <%= image_tag 'adelaide-city-white.png', class: 'hidden-xs' %>
                </div>
                <button class="navigation-toggle visible-xs" type="button" data-toggle="dropdown" data-target=".navigation-navbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navigation-navbar">
                <ul class="navigation-bar navigation-bar-left">
                    <!-- <li class="active"><a href="#hero">Home</a></li> -->
                    <li>
                        <div
                          class="fb-like"
                          data-share="true"
                          data-width="450"
                          data-show-faces="true">
                        </div>
                    </li>
                </ul>
                <% unless user_signed_in? %>
                    <!-- <ul class="navigation-bar navigation-bar-right">
                        <li><a href="register.html">Login</a></li>
                        <li class="featured"><a href="register.html">Sign up</a></li>
                    </ul>   -->
                <% end %>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/_preloader.html.erb
<div id="mask">
    <div id="loader"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Traffic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body data-action="<%= action_name %>" data-controller="<%= nice_controller_name %>" >
  <%= render 'layouts/preloader' %>    
  <%= render 'layouts/header' if controller_name == 'static' && action_name == 'index' %>
  
  <%= yield %>

  <%= render 'layouts/facebook' %>
</body>
</html>

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :route_from %><br>
    <%= f.text_field :route_from %>
  </div>
  <div class="field">
    <%= f.label :route_to %><br>
    <%= f.text_field :route_to %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<h1>Listing routes</h1>

<table>
  <thead>
    <tr>
      <th>Route from</th>
      <th>Route to</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.route_from %></td>
        <td><%= route.route_to %></td>
        <td><%= route.start_time %></td>
        <td><%= route.end_time %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Route from:</strong>
  <%= @route.route_from %>
</p>

<p>
  <strong>Route to:</strong>
  <%= @route.route_to %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @route.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @route.end_time %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>